<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ET3V8KL" failures="2" tests="3" name="Test" time="4.071" errors="0" timestamp="16 Aug 2020 06:57:48 GMT">
  <testcase classname="com.testingshastra.listenerdemo.ListenerClasstTest" name="testcase01" time="0.018"/>
  <testcase classname="com.testingshastra.listenerdemo.ListenerClasstTest" name="testcase02" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at com.testingshastra.listenerdemo.ListenerClasstTest.testcase02(ListenerClasstTest.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase02 -->
  <testcase classname="com.testingshastra.listenerdemo.ListenerClasstTest" name="testcase03" time="3.004">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at com.testingshastra.listenerdemo.ListenerClasstTest.testcase03(ListenerClasstTest.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase03 -->
</testsuite> <!-- Test -->
